#主配置文件
server:
  port: 8081
  #生产配置文件
  servlet:
    context-path: /demo1
    jsp:
      init-parameters:
        development: true #热部署
spring:
  banner:
    charset: utf-8
    location: classpath:banner.txt
#    mvc: #配置视图解析器
    #        prefix:
#      view:
#        suffix:
#创建数据库连接池
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name:  com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8
  servlet:
    multipart:
      max-request-size: 300MB
      max-file-size: 300MB
#          redis:
#            host:192.168.0.119
#            port: 7000
#            lettuce:
#              pool:
#                max-wait:-1
#                max-idle: 8
#        min-idle: 0
#        max-active: 8

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.example.entity #指定起别名的包